// ─────────────────────────────────────────────────────────────
// Fee Management → printable fee receipt.
// ─────────────────────────────────────────────────────────────
import { Link, useParams } from 'react-router-dom'
import { GlassCard, Button, Icon } from '../components/ui.jsx'
import { useFees, findReceipt } from '../store/feeStore.js'

export default function Receipt() {
  const { no } = useParams()
  const r = useFees(findReceipt(no))

  if (!r) {
    return (
      <div className="page-enter">
        <GlassCard className="p-10 text-center">
          <Icon name="SearchX" size={28} className="mx-auto text-slate-300" />
          <p className="mt-3 text-sm font-bold text-navy">Receipt “{no}” not found</p>
          <Link to="/fees/receipts" className="mt-2 inline-block text-xs font-semibold text-teal-600 hover:underline">← Back to receipts</Link>
        </GlassCard>
      </div>
    )
  }

  return (
    <div className="page-enter space-y-5">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <Link to="/fees/receipts" className="inline-flex items-center gap-1 text-xs font-semibold text-slate-500 hover:text-navy">
          <Icon name="ArrowLeft" size={14} /> Back to receipts
        </Link>
        <Button icon="Download" onClick={() => window.print()}>Download PDF</Button>
      </div>

      {/* Receipt card */}
      <div className="mx-auto max-w-lg">
        <GlassCard className="overflow-hidden p-0">
          <div className="brand-gradient px-6 py-5 text-center text-white" style={{ background: 'linear-gradient(145deg,#0F766E,#0A4A44)' }}>
            <div className="mx-auto mb-2 grid h-11 w-11 place-items-center rounded-xl bg-white/15">
              <Icon name="GraduationCap" size={22} />
            </div>
            <p className="text-lg font-bold tracking-tight">Spark College of Engineering</p>
            <p className="text-2xs uppercase tracking-[0.18em] text-teal-100/80">Official Fee Receipt</p>
          </div>

          <div className="space-y-4 p-6">
            <div className="flex items-center justify-between rounded-lg bg-slate-50 px-4 py-2.5">
              <span className="text-2xs font-semibold uppercase tracking-wider text-slate-400">Receipt No</span>
              <span className="font-mono text-sm font-bold text-navy">{r.receiptNo}</span>
            </div>

            <div className="grid grid-cols-2 gap-x-6 gap-y-4">
              <Row label="Student" value={r.name} />
              <Row label="Roll Number" value={r.roll} />
              <Row label="Amount Paid" value={`₹${r.amount.toLocaleString('en-IN')}`} strong />
              <Row label="Payment Mode" value={r.mode} />
              <Row label="Date" value={r.date} />
              <Row label="Reference" value={r.ref} />
              {r.remarks && <Row label="Remarks" value={r.remarks} />}
              <Row label="Status" value="Paid" status />
            </div>

            <div className="flex items-center justify-between border-t border-dashed border-slate-200 pt-4">
              <div className="text-2xs text-slate-400">
                <p>Generated by Spark ERP · Finance</p>
                <p>This is a computer-generated receipt.</p>
              </div>
              <div className="grid h-12 w-12 place-items-center rounded-lg border border-emerald-200 bg-emerald-50 text-emerald-600">
                <Icon name="BadgeCheck" size={26} />
              </div>
            </div>
          </div>
        </GlassCard>
      </div>
    </div>
  )
}

function Row({ label, value, strong, status }) {
  return (
    <div>
      <p className="text-2xs font-medium uppercase tracking-wider text-slate-400">{label}</p>
      {status ? (
        <span className="mt-1 inline-flex items-center rounded-md bg-emerald-50 px-2 py-0.5 text-2xs font-bold text-emerald-700 ring-1 ring-inset ring-emerald-100">{value}</span>
      ) : (
        <p className={`mt-0.5 ${strong ? 'text-base font-bold text-navy' : 'text-sm font-semibold text-navy'}`}>{value}</p>
      )}
    </div>
  )
}
